apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-kustomization-dev
resources:
- ../../base
patches:
- path: deployment.yaml
images:
- name: stefanprodan/podinfo
  newName: stefanprodan/podinfo
  newTag: 6.6.3
