apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: deployment.yaml
images:
- name: stefanprodan/podinfo:6.6.2
  newName: stefanprodan/podinfo
  newTag: 6.6.3
